# Generated by Django 5.1.6 on 2025-04-14 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syllabus',
            name='active',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='description',
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('IT', 'IT'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('MECH', 'MECH'), ('CIVIL', 'CIVIL')], max_length=10),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='regulation',
            field=models.CharField(choices=[('R17', 'R17'), ('R20', 'R20'), ('R23', 'R23')], max_length=10),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FacultyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=100)),
                ('is_approved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
