# Generated by Django 5.1.6 on 2025-04-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabus',
            name='department',
            field=models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('IT', 'Information Technology'), ('ECE', 'Electronics and Communication Engineering'), ('EEE', 'Electrical and Electronics Engineering'), ('MECH', 'Mechanical Engineering'), ('CIVIL', 'Civil Engineering')], max_length=10),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='regulation',
            field=models.CharField(choices=[('R17', 'Regulation 17'), ('R20', 'Regulation 20'), ('R23', 'Regulation 23')], max_length=10),
        ),
    ]
